export const seedPosts = [
  {
    id: 'seed-overseas-auth',
    type: 'news' as const,
    title: '재외국민, 국내 휴대전화 없이 공공 웹사이트 인증 가능해진다',
    body: '재외동포청과 행정안전부가 해외 휴대전화 번호와 전자여권을 활용한 재외국민 인증서 서비스를 개선했습니다. 등록 재외국민은 일부 민간 금융앱에서 인증서를 발급받아 국내 공공 웹사이트를 이용할 수 있습니다.',
    authorId: 'seed-editorial',
    author: '재외동포청 보도자료',
    country: 'Global',
    createdAt: '2026-05-06T09:00:00.000Z',
    views: 0,
    sourceName: '재외동포청',
    sourceUrl: 'https://www.oka.go.kr/web/board/brdDetail.do?menu_cd=000018&num=4455',
  },
  {
    id: 'seed-f4-visa',
    type: 'news' as const,
    title: '통합 F-4 비자 시행 후 3만6천여 명 재외동포 승인',
    body: '연합뉴스 보도에 따르면 통합 재외동포 비자 제도 시행 이후 3만6천여 명이 F-4 비자를 승인받았습니다. 재외동포 지원센터 확대 계획도 함께 발표됐습니다.',
    authorId: 'seed-editorial',
    author: '연합뉴스',
    country: 'Global',
    createdAt: '2026-05-27T09:00:00.000Z',
    views: 0,
    sourceName: 'Yonhap News Agency',
    sourceUrl: 'https://en.yna.co.kr/view/AEN20260527005300315',
  },
  {
    id: 'seed-driver-license',
    type: 'news' as const,
    title: '해외 운전면허 갱신·휴대전화 인증 불편 개선 추진',
    body: '재외동포청이 해외 운전면허 갱신과 휴대전화 인증 등 재외국민 민원 후속 조치를 진행하고 있습니다. 국제운전면허증 신청·수령 절차 개선도 올해 하반기 시행 계획에 포함됐습니다.',
    authorId: 'seed-editorial',
    author: '연합뉴스 동포의 창',
    country: 'Global',
    createdAt: '2026-06-01T09:00:00.000Z',
    views: 0,
    sourceName: '연합뉴스',
    sourceUrl: 'https://www.yna.co.kr/view/AKR20260601132900371',
  },
  {
    id: 'seed-voting',
    type: 'news' as const,
    title: '해외동포 우편·전자투표 검토 지시',
    body: 'Korea Herald는 해외동포의 투표 편의를 위해 우편투표와 전자투표를 검토하라는 대통령 지시가 나왔다고 보도했습니다. 지역별 우편 인프라에 맞춘 단계적 도입 가능성이 언급됐습니다.',
    authorId: 'seed-editorial',
    author: 'Korea Herald',
    country: 'Global',
    createdAt: '2026-08-05T09:00:00.000Z',
    views: 0,
    sourceName: 'The Korea Herald',
    sourceUrl: 'https://www.koreaherald.com/article/10832050',
  },
  {
    id: 'seed-bank-power',
    type: 'news' as const,
    title: '해외공관 인증 위임장 국내 은행 온라인 전달 추진',
    body: '해외공관에서 인증한 금융 위임장을 국내 은행으로 온라인 전달할 수 있도록 제도를 개선한다는 발표가 나왔습니다. 해외 거주자의 금융 업무 시간과 비용을 줄이는 것이 목적입니다.',
    authorId: 'seed-editorial',
    author: 'Seoul Economic Daily',
    country: 'Global',
    createdAt: '2026-07-30T09:00:00.000Z',
    views: 0,
    sourceName: 'Seoul Economic Daily',
    sourceUrl: 'https://en.sedaily.com/politics/2026/07/30/lee-eases-overseas-koreans-banking-hassles-why-wasnt-this',
  },
];

export const seedMarketItems = [
  { id: 'seed-iphone-16', title: 'Apple iPhone 16 128GB', price: '공식 출시가 US$799', location: 'Global · Apple Store 기준', country: 'Global', authorId: 'seed-editorial', createdAt: '2026-01-10T09:00:00.000Z', sourceName: 'Apple', sourceUrl: 'https://www.apple.com/iphone-16/' },
  { id: 'seed-macbook-air', title: 'MacBook Air 13-inch M4', price: '공식 출시가 US$999', location: 'Global · Apple Store 기준', country: 'Global', authorId: 'seed-editorial', createdAt: '2026-01-11T09:00:00.000Z', sourceName: 'Apple', sourceUrl: 'https://www.apple.com/macbook-air/' },
  { id: 'seed-galaxy-s25', title: 'Samsung Galaxy S25 256GB', price: '공식 출시가 US$799.99', location: 'USA · Samsung 기준', country: 'USA', authorId: 'seed-editorial', createdAt: '2026-01-12T09:00:00.000Z', sourceName: 'Samsung', sourceUrl: 'https://www.samsung.com/us/smartphones/galaxy-s25/' },
  { id: 'seed-switch-2', title: 'Nintendo Switch 2', price: '공식 출시가 US$449.99', location: 'Global · Nintendo 기준', country: 'Global', authorId: 'seed-editorial', createdAt: '2026-01-13T09:00:00.000Z', sourceName: 'Nintendo', sourceUrl: 'https://www.nintendo.com/us/gaming-systems/switch-2/' },
  { id: 'seed-sony-xm5', title: 'Sony WH-1000XM5', price: '공식 가격 US$399.99', location: 'Global · Sony 기준', country: 'Global', authorId: 'seed-editorial', createdAt: '2026-01-14T09:00:00.000Z', sourceName: 'Sony', sourceUrl: 'https://electronics.sony.com/audio/headphones/headband/p/wh1000xm5-b' },
];

export const seedDirectories = [
  { id: 'seed-kyochon', name: 'Kyochon Global', category: '한식 프랜차이즈', desc: '한국에서 시작한 치킨 브랜드의 공식 글로벌 사업자입니다.', tel: '+82 1577 1991', country: 'Korea', authorId: 'seed-editorial', createdAt: '2026-01-20T09:00:00.000Z', sourceName: 'Kyochon Global', sourceUrl: 'https://kyochon.com/' },
  { id: 'seed-seoul-sausage', name: 'Seoul Sausage', category: '한식·푸드', desc: '로스앤젤레스 기반의 Korean Fried Chicken, 소시지와 소스를 만드는 업체입니다.', tel: 'info@seoulsausage.com', country: 'USA', authorId: 'seed-editorial', createdAt: '2026-01-21T09:00:00.000Z', sourceName: 'Seoul Sausage', sourceUrl: 'https://seoulsausage.com/' },
  { id: 'seed-k-startup-tokyo', name: 'K-Startup Center Tokyo', category: '창업·비즈니스 지원', desc: '도쿄에서 한국 스타트업의 현지 진출과 네트워크 구축을 지원합니다.', tel: '공식 사이트 문의', country: 'Japan', authorId: 'seed-editorial', createdAt: '2026-01-22T09:00:00.000Z', sourceName: 'K-Startup Center Tokyo', sourceUrl: 'https://www.k-startup.go.kr/' },
  { id: 'seed-shanghai-school', name: 'Shanghai Korean School', category: '교육', desc: '상하이 거주 한국 학생을 위한 유치원부터 고등학교 과정의 학교입니다.', tel: '021-6493', country: 'China', authorId: 'seed-editorial', createdAt: '2026-01-23T09:00:00.000Z', sourceName: 'Shanghai Korean School', sourceUrl: 'https://skoschool.com/' },
  { id: 'seed-hancook-vietnam', name: 'HanCook Cafe & Food', category: '한식당', desc: '베트남에서 정통 한국식 구이와 음식 문화를 소개하는 식음료 업체입니다.', tel: '0236 3531 319', country: 'Vietnam', authorId: 'seed-editorial', createdAt: '2026-01-24T09:00:00.000Z', sourceName: 'HanCook Vietnam', sourceUrl: 'https://hancook.com.vn/' },
  { id: 'seed-soul-dining', name: 'SOUL Dining', category: '한식 파인다이닝', desc: '시드니에서 현지 식재료와 현대 호주 기법으로 contemporary Korean food를 선보입니다.', tel: '0431 437 059', country: 'Australia', authorId: 'seed-editorial', createdAt: '2026-01-25T09:00:00.000Z', sourceName: 'SOUL Dining', sourceUrl: 'https://souldining.com.au/' },
];
